// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivycwcjnrmlzbhyaehf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdnljd2NqbnJtbHpiaHlhZWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTc4NzQsImV4cCI6MjA2NTIzMzg3NH0.4IV9O_KKMqsPsU9LHQh-xgtwvhB_b1B4V7Ge_oE6UCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);